webtalk_init -webtalk_dir /home/fij32622/Documents/PPL--Beat-the-clock/SPI2_TB/SPI2_TB.sim/sim_1/behav/xsim/xsim.dir/Send8BitSPI2_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec  4 15:44:21 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "089c3ec9-df0d-41eb-bff1-7b4853aee72e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "489deb8d4b4f4f9486c63299f0816cd5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 10 (buster)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4403.221 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "101.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "123500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2198633144 -regid "" -xml /home/fij32622/Documents/PPL--Beat-the-clock/SPI2_TB/SPI2_TB.sim/sim_1/behav/xsim/xsim.dir/Send8BitSPI2_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/fij32622/Documents/PPL--Beat-the-clock/SPI2_TB/SPI2_TB.sim/sim_1/behav/xsim/xsim.dir/Send8BitSPI2_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/fij32622/Documents/PPL--Beat-the-clock/SPI2_TB/SPI2_TB.sim/sim_1/behav/xsim/xsim.dir/Send8BitSPI2_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
