#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jan 15 16:54:49 CET 2025
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 48a556bc3b4b478ea4a46648c3089168 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_measure_time_behav xil_defaultlib.tb_measure_time -log elaborate.log"
xelab -wto 48a556bc3b4b478ea4a46648c3089168 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_measure_time_behav xil_defaultlib.tb_measure_time -log elaborate.log

