#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Dec 05 15:45:09 CET 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Send8BitSPI2_TB_behav -key {Behavioral:sim_1:Functional:Send8BitSPI2_TB} -tclbatch Send8BitSPI2_TB.tcl -log simulate.log"
xsim Send8BitSPI2_TB_behav -key {Behavioral:sim_1:Functional:Send8BitSPI2_TB} -tclbatch Send8BitSPI2_TB.tcl -log simulate.log

