set_property SRC_FILE_INFO {cfile:/home/fij32622/Documents/SPI2_TB/SPI2_TB.srcs/constrs_1/imports/constraints/Nexys4_Master.xdc rfile:../../../SPI2_TB.srcs/constrs_1/imports/constraints/Nexys4_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports ss_out]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports mosi_top]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13 [get_ports sclk_top]
